
version: 2

models:
  - name: Subscriber_cancellation_database
    description: "Subscriber cancellation database with information about the subscriber, their course, and their job"
    columns:
      - name: student_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
